from src.user_communication import sort_vacancies, get_top_vacancies, filter_vacancies
from src.vacancies import Vacancy


def test_sort_vacancies(hh_ru):
    vacancies = [
        {
            "id": "125828331",
            "premium": False,
            "name": "Стажер / Junior BI engenineer",
            "department": None,
            "has_test": False,
            "response_letter_required": True,
            "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Нур-Султан (Астана)",
                "street": "проспект Кабанбай Батыра",
                "building": "49",
                "lat": 51.10289019613421,
                "lng": 71.40549623676974,
                "description": None,
                "raw": "Нур-Султан (Астана), проспект Кабанбай Батыра, 49",
                "metro": None,
                "metro_stations": [],
                "id": "2332192",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-09-26T09:49:32+0300",
            "created_at": "2025-09-26T09:49:32+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=125828331",
            "show_logo_in_search": None,
            "show_contacts": False,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/125828331?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/125828331",
            "relations": [],
            "employer": {
                "id": "3751916",
                "name": "Geometry",
                "url": "https://api.hh.ru/employers/3751916",
                "alternate_url": "https://hh.ru/employer/3751916",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1023246.png",
                    "90": "https://img.hhcdn.ru/employer-logo/5713752.png",
                    "240": "https://img.hhcdn.ru/employer-logo/5713753.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=3751916",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "знание инструментов визуализации данных (например, Power BI, Qlik) будет "
                "преимуществом. - Владение языками программирования (например, "
                "<highlighttext>Python</highlighttext>, R) приветствуется. - Стремление учиться, "
                "адаптироваться...",
                "responsibility": "3-недельное обучение (bootcamp): интенсивная программа с погружением в BI, "
                "практические кейсы и сопровождение менторов. 2-месячная проектная часть: "
                "участие...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "156", "name": "BI-аналитик, аналитик данных"}],
            "accept_incomplete_resumes": True,
            "experience": {"id": "noExperience", "name": "Нет опыта"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126647616",
            "premium": False,
            "name": "Аналитик данных",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Ташкент",
                "street": "улица Ислама Каримова",
                "building": "51",
                "lat": 41.310426,
                "lng": 69.248179,
                "description": None,
                "raw": "Ташкент, улица Ислама Каримова, 51",
                "metro": None,
                "metro_stations": [],
                "id": "20066097",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-17T11:50:31+0300",
            "created_at": "2025-10-17T11:50:31+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126647616",
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126647616?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126647616",
            "relations": [],
            "employer": {
                "id": "5032461",
                "name": "Raqamli Rivojlanish departamenti",
                "url": "https://api.hh.ru/employers/5032461",
                "alternate_url": "https://hh.ru/employer/5032461",
                "logo_urls": None,
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=5032461",
                "country_id": 6,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Опыт работы с BI-системами для визуализации данных (Visiology, Power BI, "
                "Tableau и пр.). Владение MS Excel. <highlighttext>Python</highlighttext>. ",
                "responsibility": "Подготовка отчетов в соответствии с запросами менеджера. Анализ структуры "
                "данных с целью их оптимизации. Сотрудничество с программистами, "
                "инженерами и руководителями...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "SIX_ON_ONE_OFF", "name": "6/1"}],
            "night_shifts": False,
            "professional_roles": [{"id": "156", "name": "BI-аналитик, аналитик данных"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126476197",
            "premium": False,
            "name": "Python-разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": True,
            "area": {"id": "160", "name": "Алматы", "url": "https://api.hh.ru/areas/160"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Алматы",
                "street": "улица Байзакова",
                "building": "280",
                "lat": 43.237242,
                "lng": 76.915075,
                "description": None,
                "raw": "Алматы, улица Байзакова, 280",
                "metro": {
                    "station_name": "Театр имени Ауэзова",
                    "line_name": "Первая",
                    "station_id": "64.435",
                    "line_id": "64",
                    "lat": 43.240362,
                    "lng": 76.917519,
                },
                "metro_stations": [
                    {
                        "station_name": "Театр имени Ауэзова",
                        "line_name": "Первая",
                        "station_id": "64.435",
                        "line_id": "64",
                        "lat": 43.240362,
                        "lng": 76.917519,
                    }
                ],
                "id": "16193675",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-13T15:03:14+0300",
            "created_at": "2025-10-13T15:03:14+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126476197",
            "show_logo_in_search": None,
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126476197?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126476197",
            "relations": [],
            "employer": {
                "id": "5783767",
                "name": "Фромтек",
                "url": "https://api.hh.ru/employers/5783767",
                "alternate_url": "https://hh.ru/employer/5783767",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1300726.png",
                    "90": "https://img.hhcdn.ru/employer-logo/6823166.png",
                    "240": "https://img.hhcdn.ru/employer-logo/6823167.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=5783767",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Знание <highlighttext>Python</highlighttext>. Условия: Опыт работы с: "
                "Backend фреймворками FastAPI/Django, реляционными базами данных, HTTP запросами, "
                "системы контроля версий Git. ",
                "responsibility": "Разработка и написание логики голосовых роботизированных помощников по "
                "скриптам коммуникации в мессенджерах, sms и т.п. с использованием "
                "собственных <highlighttext>python</highlighttext>...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "125834072",
            "premium": False,
            "name": "Стажер в Hard Code",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Астана",
                "street": "улица Сыганак",
                "building": "3/1",
                "lat": 51.13265,
                "lng": 71.371275,
                "description": None,
                "raw": "Астана, улица Сыганак, 3/1",
                "metro": None,
                "metro_stations": [],
                "id": "16857473",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-09-26T11:21:29+0300",
            "created_at": "2025-09-26T11:21:29+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=125834072",
            "show_logo_in_search": None,
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/125834072?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/125834072",
            "relations": [],
            "employer": {
                "id": "4452595",
                "name": "Hard Code",
                "url": "https://api.hh.ru/employers/4452595",
                "alternate_url": "https://hh.ru/employer/4452595",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/707931.png",
                    "90": "https://img.hhcdn.ru/employer-logo/3272840.png",
                    "240": "https://img.hhcdn.ru/employer-logo/3272841.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=4452595",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Кандидат должен иметь базовый опыт разработки или программирования на "
                "одном из современных языков программирования, таких как C#, Java, "
                "<highlighttext>Python</highlighttext>, JavaScript...",
                "responsibility": "Компания Hardcode является поставщиком услуг по разработке программного "
                "обеспечения и автоматизации процессов для предприятий и промышленных "
                "производств. Мы ведем полный...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [
                {"id": "from_four_to_six_hours_in_a_day", "name": "Можно сменами по\xa04-6\xa0часов в\xa0день"}
            ],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_6", "name": "6\xa0часов"}, {"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}, {"id": "OTHER", "name": "Другое"}],
            "night_shifts": False,
            "professional_roles": [{"id": "40", "name": "Другое"}],
            "accept_incomplete_resumes": True,
            "experience": {"id": "noExperience", "name": "Нет опыта"},
            "employment": {"id": "part", "name": "Частичная занятость"},
            "employment_form": {"id": "PART", "name": "Частичная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126619317",
            "premium": False,
            "name": "Strong Middle Backend Engineer (Python)",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": {"from": 2500, "to": 3600, "currency": "USD", "gross": True},
            "salary_range": {
                "from": 2500,
                "to": 3600,
                "currency": "USD",
                "gross": True,
                "mode": {"id": "MONTH", "name": "За\xa0месяц"},
                "frequency": {"id": "MONTHLY", "name": "Раз в\xa0месяц"},
            },
            "type": {"id": "open", "name": "Открытая"},
            "address": None,
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-16T15:37:41+0300",
            "created_at": "2025-10-16T15:37:41+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126619317",
            "show_logo_in_search": None,
            "show_contacts": False,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126619317?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126619317",
            "relations": [],
            "employer": {
                "id": "9554799",
                "name": "Super Dispatch (ООО Software Transport)",
                "url": "https://api.hh.ru/employers/9554799",
                "alternate_url": "https://hh.ru/employer/9554799",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1055110.jpeg",
                    "90": "https://img.hhcdn.ru/employer-logo/5841081.jpeg",
                    "240": "https://img.hhcdn.ru/employer-logo/5841082.jpeg",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9554799",
                "country_id": 6,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "...one <highlighttext>Python</highlighttext> web framework, such as Django, "
                "FastApi, etc. and willing to build and maintain services in different "
                "<highlighttext>Python</highlighttext> web...",
                "responsibility": "Work closely with your team (design, engineering, product, analytics) to "
                "figure out and deliver innovative solutions that will drive your...",
            },
            "contacts": None,
            "schedule": {"id": "remote", "name": "Удаленная работа"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": True,
            "fly_in_fly_out_duration": [],
            "work_format": [
                {"id": "REMOTE", "name": "Удалённо"},
                {"id": "HYBRID", "name": "Гибрид"},
                {"id": "FIELD_WORK", "name": "Разъездной"},
            ],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126599052",
            "premium": False,
            "name": "Backend - разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
            "salary": {"from": 500000, "to": 1000000, "currency": "KZT", "gross": False},
            "salary_range": {
                "from": 500000,
                "to": 1000000,
                "currency": "KZT",
                "gross": False,
                "mode": {"id": "MONTH", "name": "За\xa0месяц"},
                "frequency": None,
            },
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Астана",
                "street": "улица Достык",
                "building": "16",
                "lat": 51.124736,
                "lng": 71.432082,
                "description": None,
                "raw": "Астана, улица Достык, 16",
                "metro": None,
                "metro_stations": [],
                "id": "14764405",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-16T10:20:18+0300",
            "created_at": "2025-10-16T10:20:18+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126599052",
            "show_logo_in_search": None,
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126599052?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126599052",
            "relations": [],
            "employer": {
                "id": "10584232",
                "name": "DLS-Global KZ",
                "url": "https://api.hh.ru/employers/10584232",
                "alternate_url": "https://hh.ru/employer/10584232",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1281717.jpg",
                    "90": "https://img.hhcdn.ru/employer-logo/6747166.jpeg",
                    "240": "https://img.hhcdn.ru/employer-logo/6747167.jpeg",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=10584232",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "3+ года коммерческой разработки на <highlighttext>Python</highlighttext> "
                "(Django). Опыт проектирования и реализации нового функционала, REST API "
                "и интеграций с внешними...",
                "responsibility": "Разработка нового функционала и сервисов на "
                "<highlighttext>Python</highlighttext>/Django с “нуля” до продакшена. Разработка, "
                "документирование и отладка REST API для мобильных...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
    ]

    vacancies_list = [Vacancy.cast_to_object_list(v) for v in vacancies]
    sorted_vacancies = sort_vacancies(vacancies_list)
    assert [vacancy.salary for vacancy in sorted_vacancies] == [298800, 150000.0, 0, 0, 0, 0]


def test_get_top_vacancies(hh_ru):
    vacancies = [
        {
            "id": "125828331",
            "premium": False,
            "name": "Стажер / Junior BI engenineer",
            "department": None,
            "has_test": False,
            "response_letter_required": True,
            "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Нур-Султан (Астана)",
                "street": "проспект Кабанбай Батыра",
                "building": "49",
                "lat": 51.10289019613421,
                "lng": 71.40549623676974,
                "description": None,
                "raw": "Нур-Султан (Астана), проспект Кабанбай Батыра, 49",
                "metro": None,
                "metro_stations": [],
                "id": "2332192",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-09-26T09:49:32+0300",
            "created_at": "2025-09-26T09:49:32+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=125828331",
            "show_logo_in_search": None,
            "show_contacts": False,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/125828331?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/125828331",
            "relations": [],
            "employer": {
                "id": "3751916",
                "name": "Geometry",
                "url": "https://api.hh.ru/employers/3751916",
                "alternate_url": "https://hh.ru/employer/3751916",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1023246.png",
                    "90": "https://img.hhcdn.ru/employer-logo/5713752.png",
                    "240": "https://img.hhcdn.ru/employer-logo/5713753.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=3751916",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "знание инструментов визуализации данных (например, Power BI, Qlik) будет "
                "преимуществом. - Владение языками программирования (например, "
                "<highlighttext>Python</highlighttext>, R) приветствуется. - Стремление учиться, "
                "адаптироваться...",
                "responsibility": "3-недельное обучение (bootcamp): интенсивная программа с погружением в BI, "
                "практические кейсы и сопровождение менторов. 2-месячная проектная часть: участие...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "156", "name": "BI-аналитик, аналитик данных"}],
            "accept_incomplete_resumes": True,
            "experience": {"id": "noExperience", "name": "Нет опыта"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126647616",
            "premium": False,
            "name": "Аналитик данных",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Ташкент",
                "street": "улица Ислама Каримова",
                "building": "51",
                "lat": 41.310426,
                "lng": 69.248179,
                "description": None,
                "raw": "Ташкент, улица Ислама Каримова, 51",
                "metro": None,
                "metro_stations": [],
                "id": "20066097",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-17T11:50:31+0300",
            "created_at": "2025-10-17T11:50:31+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126647616",
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126647616?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126647616",
            "relations": [],
            "employer": {
                "id": "5032461",
                "name": "Raqamli Rivojlanish departamenti",
                "url": "https://api.hh.ru/employers/5032461",
                "alternate_url": "https://hh.ru/employer/5032461",
                "logo_urls": None,
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=5032461",
                "country_id": 6,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Опыт работы с BI-системами для визуализации данных (Visiology, Power BI, "
                "Tableau и пр.). Владение MS Excel. <highlighttext>Python</highlighttext>. ",
                "responsibility": "Подготовка отчетов в соответствии с запросами менеджера. Анализ структуры "
                "данных с целью их оптимизации. Сотрудничество с программистами, инженерами и руководителями...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "SIX_ON_ONE_OFF", "name": "6/1"}],
            "night_shifts": False,
            "professional_roles": [{"id": "156", "name": "BI-аналитик, аналитик данных"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126476197",
            "premium": False,
            "name": "Python-разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": True,
            "area": {"id": "160", "name": "Алматы", "url": "https://api.hh.ru/areas/160"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Алматы",
                "street": "улица Байзакова",
                "building": "280",
                "lat": 43.237242,
                "lng": 76.915075,
                "description": None,
                "raw": "Алматы, улица Байзакова, 280",
                "metro": {
                    "station_name": "Театр имени Ауэзова",
                    "line_name": "Первая",
                    "station_id": "64.435",
                    "line_id": "64",
                    "lat": 43.240362,
                    "lng": 76.917519,
                },
                "metro_stations": [
                    {
                        "station_name": "Театр имени Ауэзова",
                        "line_name": "Первая",
                        "station_id": "64.435",
                        "line_id": "64",
                        "lat": 43.240362,
                        "lng": 76.917519,
                    }
                ],
                "id": "16193675",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-13T15:03:14+0300",
            "created_at": "2025-10-13T15:03:14+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126476197",
            "show_logo_in_search": None,
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126476197?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126476197",
            "relations": [],
            "employer": {
                "id": "5783767",
                "name": "Фромтек",
                "url": "https://api.hh.ru/employers/5783767",
                "alternate_url": "https://hh.ru/employer/5783767",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1300726.png",
                    "90": "https://img.hhcdn.ru/employer-logo/6823166.png",
                    "240": "https://img.hhcdn.ru/employer-logo/6823167.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=5783767",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Знание <highlighttext>Python</highlighttext>. Условия: Опыт работы с: "
                "Backend фреймворками FastAPI/Django, реляционными базами данных, HTTP запросами, "
                "системы контроля версий Git. ",
                "responsibility": "Разработка и написание логики голосовых роботизированных помощников по скриптам "
                "коммуникации в мессенджерах, sms и т.п. с использованием собственных "
                                  "<highlighttext>python</highlighttext>...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "125834072",
            "premium": False,
            "name": "Стажер в Hard Code",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Астана",
                "street": "улица Сыганак",
                "building": "3/1",
                "lat": 51.13265,
                "lng": 71.371275,
                "description": None,
                "raw": "Астана, улица Сыганак, 3/1",
                "metro": None,
                "metro_stations": [],
                "id": "16857473",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-09-26T11:21:29+0300",
            "created_at": "2025-09-26T11:21:29+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=125834072",
            "show_logo_in_search": None,
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/125834072?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/125834072",
            "relations": [],
            "employer": {
                "id": "4452595",
                "name": "Hard Code",
                "url": "https://api.hh.ru/employers/4452595",
                "alternate_url": "https://hh.ru/employer/4452595",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/707931.png",
                    "90": "https://img.hhcdn.ru/employer-logo/3272840.png",
                    "240": "https://img.hhcdn.ru/employer-logo/3272841.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=4452595",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Кандидат должен иметь базовый опыт разработки или программирования "
                "на одном из современных языков программирования, таких как C#, Java, "
                "<highlighttext>Python</highlighttext>, JavaScript...",
                "responsibility": "Компания Hardcode является поставщиком услуг по разработке программного "
                "обеспечения и автоматизации процессов для предприятий и промышленных производств. "
                "Мы ведем полный...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [
                {"id": "from_four_to_six_hours_in_a_day", "name": "Можно сменами по\xa04-6\xa0часов в\xa0день"}
            ],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_6", "name": "6\xa0часов"}, {"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}, {"id": "OTHER", "name": "Другое"}],
            "night_shifts": False,
            "professional_roles": [{"id": "40", "name": "Другое"}],
            "accept_incomplete_resumes": True,
            "experience": {"id": "noExperience", "name": "Нет опыта"},
            "employment": {"id": "part", "name": "Частичная занятость"},
            "employment_form": {"id": "PART", "name": "Частичная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126619317",
            "premium": False,
            "name": "Strong Middle Backend Engineer (Python)",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": {"from": 2500, "to": 3600, "currency": "USD", "gross": True},
            "salary_range": {
                "from": 2500,
                "to": 3600,
                "currency": "USD",
                "gross": True,
                "mode": {"id": "MONTH", "name": "За\xa0месяц"},
                "frequency": {"id": "MONTHLY", "name": "Раз в\xa0месяц"},
            },
            "type": {"id": "open", "name": "Открытая"},
            "address": None,
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-16T15:37:41+0300",
            "created_at": "2025-10-16T15:37:41+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126619317",
            "show_logo_in_search": None,
            "show_contacts": False,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126619317?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126619317",
            "relations": [],
            "employer": {
                "id": "9554799",
                "name": "Super Dispatch (ООО Software Transport)",
                "url": "https://api.hh.ru/employers/9554799",
                "alternate_url": "https://hh.ru/employer/9554799",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1055110.jpeg",
                    "90": "https://img.hhcdn.ru/employer-logo/5841081.jpeg",
                    "240": "https://img.hhcdn.ru/employer-logo/5841082.jpeg",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9554799",
                "country_id": 6,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "...one <highlighttext>Python</highlighttext> web framework, such as Django, "
                "FastApi, etc. and willing to build and maintain services in different "
                "<highlighttext>Python</highlighttext> web...",
                "responsibility": "Work closely with your team (design, engineering, product, analytics) "
                "to figure out and deliver innovative solutions that will drive your...",
            },
            "contacts": None,
            "schedule": {"id": "remote", "name": "Удаленная работа"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": True,
            "fly_in_fly_out_duration": [],
            "work_format": [
                {"id": "REMOTE", "name": "Удалённо"},
                {"id": "HYBRID", "name": "Гибрид"},
                {"id": "FIELD_WORK", "name": "Разъездной"},
            ],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126599052",
            "premium": False,
            "name": "Backend - разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
            "salary": {"from": 500000, "to": 1000000, "currency": "KZT", "gross": False},
            "salary_range": {
                "from": 500000,
                "to": 1000000,
                "currency": "KZT",
                "gross": False,
                "mode": {"id": "MONTH", "name": "За\xa0месяц"},
                "frequency": None,
            },
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Астана",
                "street": "улица Достык",
                "building": "16",
                "lat": 51.124736,
                "lng": 71.432082,
                "description": None,
                "raw": "Астана, улица Достык, 16",
                "metro": None,
                "metro_stations": [],
                "id": "14764405",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-16T10:20:18+0300",
            "created_at": "2025-10-16T10:20:18+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126599052",
            "show_logo_in_search": None,
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126599052?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126599052",
            "relations": [],
            "employer": {
                "id": "10584232",
                "name": "DLS-Global KZ",
                "url": "https://api.hh.ru/employers/10584232",
                "alternate_url": "https://hh.ru/employer/10584232",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1281717.jpg",
                    "90": "https://img.hhcdn.ru/employer-logo/6747166.jpeg",
                    "240": "https://img.hhcdn.ru/employer-logo/6747167.jpeg",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=10584232",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "3+ года коммерческой разработки на <highlighttext>Python</highlighttext> "
                "(Django). Опыт проектирования и реализации нового функционала, REST API и интеграций с внешними...",
                "responsibility": "Разработка нового функционала и сервисов на "
                                  "<highlighttext>Python</highlighttext>/Django "
                "с “нуля” до продакшена. Разработка, документирование и отладка REST API для мобильных...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
    ]

    vacancies_list = [Vacancy.cast_to_object_list(v) for v in vacancies]
    top_n_vacancies = get_top_vacancies(vacancies_list, 3)
    assert len(top_n_vacancies) == 3


def test_filter_vacancies(hh_ru):
    vacancies = [
        {
            "id": "125828331",
            "premium": False,
            "name": "Стажер / Junior BI engenineer",
            "department": None,
            "has_test": False,
            "response_letter_required": True,
            "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Нур-Султан (Астана)",
                "street": "проспект Кабанбай Батыра",
                "building": "49",
                "lat": 51.10289019613421,
                "lng": 71.40549623676974,
                "description": None,
                "raw": "Нур-Султан (Астана), проспект Кабанбай Батыра, 49",
                "metro": None,
                "metro_stations": [],
                "id": "2332192",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-09-26T09:49:32+0300",
            "created_at": "2025-09-26T09:49:32+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=125828331",
            "show_logo_in_search": None,
            "show_contacts": False,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/125828331?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/125828331",
            "relations": [],
            "employer": {
                "id": "3751916",
                "name": "Geometry",
                "url": "https://api.hh.ru/employers/3751916",
                "alternate_url": "https://hh.ru/employer/3751916",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1023246.png",
                    "90": "https://img.hhcdn.ru/employer-logo/5713752.png",
                    "240": "https://img.hhcdn.ru/employer-logo/5713753.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=3751916",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "знание инструментов визуализации данных (например, Power BI, Qlik) будет "
                "преимуществом. - Владение языками программирования (например, "
                "<highlighttext>Python</highlighttext>, R) приветствуется. - Стремление учиться, адаптироваться...",
                "responsibility": "3-недельное обучение (bootcamp): интенсивная программа с погружением в BI, "
                "практические кейсы и сопровождение менторов. 2-месячная проектная часть: участие...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "156", "name": "BI-аналитик, аналитик данных"}],
            "accept_incomplete_resumes": True,
            "experience": {"id": "noExperience", "name": "Нет опыта"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126647616",
            "premium": False,
            "name": "Аналитик данных",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Ташкент",
                "street": "улица Ислама Каримова",
                "building": "51",
                "lat": 41.310426,
                "lng": 69.248179,
                "description": None,
                "raw": "Ташкент, улица Ислама Каримова, 51",
                "metro": None,
                "metro_stations": [],
                "id": "20066097",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-17T11:50:31+0300",
            "created_at": "2025-10-17T11:50:31+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126647616",
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126647616?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126647616",
            "relations": [],
            "employer": {
                "id": "5032461",
                "name": "Raqamli Rivojlanish departamenti",
                "url": "https://api.hh.ru/employers/5032461",
                "alternate_url": "https://hh.ru/employer/5032461",
                "logo_urls": None,
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=5032461",
                "country_id": 6,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Опыт работы с BI-системами для визуализации данных (Visiology, Power BI, "
                               "Tableau и пр.). Владение MS Excel. <highlighttext>Python</highlighttext>. ",
                "responsibility": "Подготовка отчетов в соответствии с запросами менеджера. Анализ структуры "
                                  "данных с целью их оптимизации. Сотрудничество с программистами, инженерами "
                                  "и руководителями...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "SIX_ON_ONE_OFF", "name": "6/1"}],
            "night_shifts": False,
            "professional_roles": [{"id": "156", "name": "BI-аналитик, аналитик данных"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126476197",
            "premium": False,
            "name": "Python-разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": True,
            "area": {"id": "160", "name": "Алматы", "url": "https://api.hh.ru/areas/160"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Алматы",
                "street": "улица Байзакова",
                "building": "280",
                "lat": 43.237242,
                "lng": 76.915075,
                "description": None,
                "raw": "Алматы, улица Байзакова, 280",
                "metro": {
                    "station_name": "Театр имени Ауэзова",
                    "line_name": "Первая",
                    "station_id": "64.435",
                    "line_id": "64",
                    "lat": 43.240362,
                    "lng": 76.917519,
                },
                "metro_stations": [
                    {
                        "station_name": "Театр имени Ауэзова",
                        "line_name": "Первая",
                        "station_id": "64.435",
                        "line_id": "64",
                        "lat": 43.240362,
                        "lng": 76.917519,
                    }
                ],
                "id": "16193675",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-13T15:03:14+0300",
            "created_at": "2025-10-13T15:03:14+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126476197",
            "show_logo_in_search": None,
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126476197?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126476197",
            "relations": [],
            "employer": {
                "id": "5783767",
                "name": "Фромтек",
                "url": "https://api.hh.ru/employers/5783767",
                "alternate_url": "https://hh.ru/employer/5783767",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1300726.png",
                    "90": "https://img.hhcdn.ru/employer-logo/6823166.png",
                    "240": "https://img.hhcdn.ru/employer-logo/6823167.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=5783767",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Знание <highlighttext>Python</highlighttext>. Условия: Опыт работы с: "
                "Backend фреймворками FastAPI/Django, реляционными базами данных, HTTP запросами, "
                "системы контроля версий Git. ",
                "responsibility": "Разработка и написание логики голосовых роботизированных помощников по скриптам "
                "коммуникации в мессенджерах, sms и т.п. с использованием собственных "
                "<highlighttext>python</highlighttext>...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between1And3", "name": "От 1 года до 3 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "125834072",
            "premium": False,
            "name": "Стажер в Hard Code",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
            "salary": None,
            "salary_range": None,
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Астана",
                "street": "улица Сыганак",
                "building": "3/1",
                "lat": 51.13265,
                "lng": 71.371275,
                "description": None,
                "raw": "Астана, улица Сыганак, 3/1",
                "metro": None,
                "metro_stations": [],
                "id": "16857473",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-09-26T11:21:29+0300",
            "created_at": "2025-09-26T11:21:29+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=125834072",
            "show_logo_in_search": None,
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/125834072?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/125834072",
            "relations": [],
            "employer": {
                "id": "4452595",
                "name": "Hard Code",
                "url": "https://api.hh.ru/employers/4452595",
                "alternate_url": "https://hh.ru/employer/4452595",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/707931.png",
                    "90": "https://img.hhcdn.ru/employer-logo/3272840.png",
                    "240": "https://img.hhcdn.ru/employer-logo/3272841.png",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=4452595",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "Кандидат должен иметь базовый опыт разработки или программирования на одном из "
                "современных языков программирования, таких как C#, Java, "
                "<highlighttext>Python</highlighttext>, JavaScript...",
                "responsibility": "Компания Hardcode является поставщиком услуг по разработке программного "
                                  "обеспечения "
                "и автоматизации процессов для предприятий и промышленных производств. Мы ведем полный...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [
                {"id": "from_four_to_six_hours_in_a_day", "name": "Можно сменами по\xa04-6\xa0часов в\xa0день"}
            ],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_6", "name": "6\xa0часов"}, {"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}, {"id": "OTHER", "name": "Другое"}],
            "night_shifts": False,
            "professional_roles": [{"id": "40", "name": "Другое"}],
            "accept_incomplete_resumes": True,
            "experience": {"id": "noExperience", "name": "Нет опыта"},
            "employment": {"id": "part", "name": "Частичная занятость"},
            "employment_form": {"id": "PART", "name": "Частичная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126619317",
            "premium": False,
            "name": "Strong Middle Backend Engineer (Python)",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "2759", "name": "Ташкент", "url": "https://api.hh.ru/areas/2759"},
            "salary": {"from": 2500, "to": 3600, "currency": "USD", "gross": True},
            "salary_range": {
                "from": 2500,
                "to": 3600,
                "currency": "USD",
                "gross": True,
                "mode": {"id": "MONTH", "name": "За\xa0месяц"},
                "frequency": {"id": "MONTHLY", "name": "Раз в\xa0месяц"},
            },
            "type": {"id": "open", "name": "Открытая"},
            "address": None,
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-16T15:37:41+0300",
            "created_at": "2025-10-16T15:37:41+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126619317",
            "show_logo_in_search": None,
            "show_contacts": False,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126619317?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126619317",
            "relations": [],
            "employer": {
                "id": "9554799",
                "name": "Super Dispatch (ООО Software Transport)",
                "url": "https://api.hh.ru/employers/9554799",
                "alternate_url": "https://hh.ru/employer/9554799",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1055110.jpeg",
                    "90": "https://img.hhcdn.ru/employer-logo/5841081.jpeg",
                    "240": "https://img.hhcdn.ru/employer-logo/5841082.jpeg",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9554799",
                "country_id": 6,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "...one <highlighttext>Python</highlighttext> web framework, such as "
                "Django, FastApi, etc. and willing to build and maintain services in different "
                "<highlighttext>Python</highlighttext> web...",
                "responsibility": "Work closely with your team (design, engineering, product, analytics) to figure "
                "out and deliver innovative solutions that will drive your...",
            },
            "contacts": None,
            "schedule": {"id": "remote", "name": "Удаленная работа"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": True,
            "fly_in_fly_out_duration": [],
            "work_format": [
                {"id": "REMOTE", "name": "Удалённо"},
                {"id": "HYBRID", "name": "Гибрид"},
                {"id": "FIELD_WORK", "name": "Разъездной"},
            ],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": False,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
        {
            "id": "126599052",
            "premium": False,
            "name": "Backend - разработчик",
            "department": None,
            "has_test": False,
            "response_letter_required": False,
            "area": {"id": "159", "name": "Астана", "url": "https://api.hh.ru/areas/159"},
            "salary": {"from": 500000, "to": 1000000, "currency": "KZT", "gross": False},
            "salary_range": {
                "from": 500000,
                "to": 1000000,
                "currency": "KZT",
                "gross": False,
                "mode": {"id": "MONTH", "name": "За\xa0месяц"},
                "frequency": None,
            },
            "type": {"id": "open", "name": "Открытая"},
            "address": {
                "city": "Астана",
                "street": "улица Достык",
                "building": "16",
                "lat": 51.124736,
                "lng": 71.432082,
                "description": None,
                "raw": "Астана, улица Достык, 16",
                "metro": None,
                "metro_stations": [],
                "id": "14764405",
            },
            "response_url": None,
            "sort_point_distance": None,
            "published_at": "2025-10-16T10:20:18+0300",
            "created_at": "2025-10-16T10:20:18+0300",
            "archived": False,
            "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=126599052",
            "show_logo_in_search": None,
            "show_contacts": True,
            "insider_interview": None,
            "url": "https://api.hh.ru/vacancies/126599052?host=hh.ru",
            "alternate_url": "https://hh.ru/vacancy/126599052",
            "relations": [],
            "employer": {
                "id": "10584232",
                "name": "DLS-Global KZ",
                "url": "https://api.hh.ru/employers/10584232",
                "alternate_url": "https://hh.ru/employer/10584232",
                "logo_urls": {
                    "original": "https://img.hhcdn.ru/employer-logo-original/1281717.jpg",
                    "90": "https://img.hhcdn.ru/employer-logo/6747166.jpeg",
                    "240": "https://img.hhcdn.ru/employer-logo/6747167.jpeg",
                },
                "vacancies_url": "https://api.hh.ru/vacancies?employer_id=10584232",
                "country_id": 3,
                "accredited_it_employer": False,
                "trusted": True,
            },
            "snippet": {
                "requirement": "3+ года коммерческой разработки на <highlighttext>Python</highlighttext> "
                "(Django). Опыт проектирования и реализации нового функционала, REST API и "
                "интеграций с внешними...",
                "responsibility": "Разработка нового функционала и сервисов на "
                "<highlighttext>Python</highlighttext>/Django с “нуля” до продакшена. Разработка, "
                "документирование и отладка REST API для мобильных...",
            },
            "contacts": None,
            "schedule": {"id": "fullDay", "name": "Полный день"},
            "working_days": [],
            "working_time_intervals": [],
            "working_time_modes": [],
            "accept_temporary": False,
            "fly_in_fly_out_duration": [],
            "work_format": [{"id": "ON_SITE", "name": "На\xa0месте работодателя"}],
            "working_hours": [{"id": "HOURS_8", "name": "8\xa0часов"}],
            "work_schedule_by_days": [{"id": "FIVE_ON_TWO_OFF", "name": "5/2"}],
            "night_shifts": False,
            "professional_roles": [{"id": "96", "name": "Программист, разработчик"}],
            "accept_incomplete_resumes": False,
            "experience": {"id": "between3And6", "name": "От 3 до 6 лет"},
            "employment": {"id": "full", "name": "Полная занятость"},
            "employment_form": {"id": "FULL", "name": "Полная"},
            "internship": True,
            "adv_response_url": None,
            "is_adv_vacancy": False,
            "adv_context": None,
        },
    ]

    vacancies_list = [Vacancy.cast_to_object_list(vacancy) for vacancy in vacancies]
    filter_words = "опыт".lower().split()
    filtered_vacancies = filter_vacancies(vacancies_list, filter_words)
    assert len(filtered_vacancies) <= len(vacancies_list)
